### ISSUE TITLE
Function | Expression instead of file I/O

### ISSUE THREAD

**Issue by JohnCoene** [kcf-jackson/sketch#2]
Hi Jackson,

This is a brilliant package that could very well make a great difference in the R world! R can now work in many ways with JavaScript but one annoying thing is having to write functions and the like as character strings.

Do you think you could extend the package so that instead of taking a file input could also accept an R function or expression which it would return as a string? That would allow using sketch for htmlwidgets, V8, bubble, even Shiny.

```r
foo <- function(id){
  document$getElementById(id)
}

compile_r(foo)
#> foo = function(id){
#>   document.getElementById(id);
#> }
```

Thanks again for the amazing work!

**Comment by kcf-jackson** [comment]
Hi John,

Thanks for the feedback! The package can certainly handle taking R expressions as input, since the `compile_r` function actually parses the input file into R expressions before it does anything. This can be seen in the source:
```
# sketch::compile_r
function(input, output = "") {
  parse(file = input) %>%
    purrr::map(rewrite) %>%
    purrr::map(deparse_js) %>%
    unlist() %>%
    write(file = output)
  output
}
```
I'll consider adding a function that does the "inline" style transpilation in the next round of development. Do you have an actual use case in mind already? I am concerned that such function may encourage an usage with `eval`, which requires extra caution.

P.S. I only found this issue earlier today buried in the long list of github notifications...rest assured that this project is still actively maintained!

**Comment by JohnCoene** [comment]
Hi Jackson,

Thanks for getting back to me on this!

I was thinking three things, 1) [htmlwidgets](http://www.htmlwidgets.org/), 2) [V8](https://github.com/jeroen/v8) by @jeroen (he might also have inputs on this), 3) [bubble](https://github.com/ColinFay/bubble/) by @ColinFay, where I reference [sketch in an issue](https://github.com/ColinFay/bubble/issues/8) and a pull request.

All of the above use JavaScript but all of it must be passed as strings which is far from ideal and unintuitive for R users, e.g.: in [echarts4r](https://echarts4r.john-coene.com/) I provide a way to customise tooltips in JavaScript but it leads to very clunky, unclean code.

I'm sure sketch would be amazing for it! Your concern seems valid though.

**Comment by kcf-jackson** [comment]
Hi John,

As the package has just been accepted at CRAN 🎉  (and so the R component of the package should stay stable at least until v1.5), I would like to make a note and address this issue now.

The function `compile_exprs` has been created to do the same thing as `compile_r` except it takes a string as input and returns a string as output. 
```{r}
library(sketch)
compile_exprs("foo <- function(id) { document$getElementById(id) }")
#[1] "foo = function(id) {\n    document.getElementById(id)\n}"
```

The major change that has happened as the package reaches 1.0 is that almost every part of the transpiler can be accessed and configured. If you prefer to work with expression rather than string, you can directly use the `rewrite` and `deparse_js` functions. (`rewrite` maps R ast to R ast, and `deparse_js`maps R ast to string. Both of them can be configured. You may find this [article](https://kcf-jackson.github.io/sketch-doc/docs/customisation) helpful. The website itself is still work-in-progress.)
```{r}
library(magrittr)
library(sketch)

R_expr <- parse_expr("foo <- function(id){
    document$getElementById(id)
}") 
R_expr %>% 
    rewrite(rules = basic_rules()) %>% 
    deparse_js(deparsers = basic_deparsers())
# [1] "foo = function(id) {\n    document.getElementById(id)\n}"
```

As I am collecting use cases for this package, please do let me know if you make something cool with it!

P.S. I watched your talk at Shiny Developer Series and @ColinFay's talk at Lander Analytics not long ago. Lots of great tips. 👍

**Comment by JohnCoene** [comment]
Fantastic work, I love it!
